### ISSUE TITLE
Quicker way to copy the Path to current file::line number

### ISSUE THREAD

**Issue by salarmehr** [kstenschke/referencer-plugin#1]
Thanks a lot for your plugin.

Is there any way to add a simple shortcut to copy the path to current file::line number?

**Comment by kstenschke** [comment]
Hi Reza, 
the quickest way for just copying "file::line number" in recent versions of the IDE is built-in: Main menu: Edit > Copy Reference. You can change the related keyboard shortcut in the IDE settings.

**Comment by kstenschke** [comment]
Hi Reza, 
the quickest way for just copying "file::line number" in recent versions of the IDE is built-in: Main menu: Edit > Copy Reference. You can change the related keyboard shortcut in the IDE settings.

**Comment by kstenschke** [comment]
Hi Reza, 
the quickest way for just copying "file::line number" in recent versions of the IDE is built-in: Main menu: Edit > Copy Reference. You can change the related keyboard shortcut in the IDE settings.

**Comment by salarmehr** [comment]
Thanks for the answer. when the plugin is enabled ctrl+shift+alt+c once does not append the line number to path.

**Comment by kstenschke** [comment]
With the referencer plugin, there are multiple options of what to copy (or paste) to chose from. 
Just press CTRL+SHIFT+ALT+c twice ((or SHIFT+ALT+CMD+c on mac OS), and a popup with options of what to copy will open. Pressing CTRL+SHIFT+ALT+v twice allows you to paste an option into the currently open file.
